# Generated by Django 6.1.1 on 2026-10-04 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producturl',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(help_text='e.g. 2-4 business days', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage, e.g. 18.00 for 18%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_information',
            field=models.TextField(blank=True, help_text='Any additional required product details'),
        ),
        migrations.AlterField(
            model_name='product',
            name='other_taxes',
            field=models.TextField(blank=True, help_text='Other applicable tax details (e.g., Cess, surcharge)'),
        ),
    ]
