# Generated by Django 6.1.1 on 2026-10-05 04:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Base price cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Delivery charges cannot be negative.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage, e.g. 18.00 for 18%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='GST cannot be negative.'), django.core.validators.MaxValueValidator(Decimal('100.00'), message='GST cannot exceed 100%.')]),
        ),
    ]
