# Generated by Django 6.1.1 on 2026-10-05 04:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_created_by_alter_product_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery charges in Rs.  (maximum 100)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Delivery charges cannot be negative.'), django.core.validators.MaxValueValidator(Decimal('100.00'), message='Delivery charges cannot exceed 100.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_time',
            field=models.CharField(help_text='e.g. 3-5 Business Days (auto-set by delivery type)', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST percentage, e.g. 18.00 for 18% (maximum 18%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='GST cannot be negative.'), django.core.validators.MaxValueValidator(Decimal('18.00'), message='GST cannot exceed 18%.')]),
        ),
    ]
