# Generated by Django 6.1.1 on 2026-10-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_delivery_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when product was soft-deleted', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating if product is soft-deleted'),
        ),
    ]
